version: '3'

volumes:
  tasks_postgres_data:
    driver: local
  auth_postgres_data:
    driver: local
  jwt_redis_data:
    driver: local
  notification_rabbitmq_data:
    driver: local

services:
  task_postgres:
    image: postgres:15.6
    container_name: task_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_TASKS_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_TASKS_PASSWORD}
      - POSTGRES_DB=${POSTGRES_TASKS_DB}
    ports:
      - "5430:5432"
    volumes:
      - tasks_postgres_data:/var/lib/postgresql/data

  auth_postgres:
    image: postgres:15.6
    container_name: auth_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_AUTH_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_AUTH_PASSWORD}
      - POSTGRES_DB=${POSTGRES_AUTH_DB}
    ports:
      - "5428:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4
    container_name: redis_container
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - jwt_redis_data:/var/lib/redis/data/jwt

  rabbit_mq:
    image: rabbitmq:3.13.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - notification_rabbitmq_data:/var/liv/rabbit/data/notification