version: '3'

volumes:
  tasks_postgres_data:
    driver: local
  auth_postgres_data:
    driver: local

services:
  task_postgres:
    image: postgres:15.6
    container_name: task_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_TASKS_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_TASKS_PASSWORD}
      - POSTGRES_DB=${POSTGRES_TASKS_DB}
    ports:
      - "5430:5432"
    volumes:
      - tasks_postgres_data:/var/lib/postgresql/data

  auth_postgres:
    image: postgres:15.6
    container_name: auth_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_AUTH_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_AUTH_PASSWORD}
      - POSTGRES_DB=${POSTGRES_AUTH_DB}
    ports:
      - "5428:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data