server:
  port: 8989

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**

        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/api/v1/tasks/**