spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    port: ${RABBITMQ_PORT}

email-exchange:
  name: email-exchange
  queues:
    - name: auth_user_email_queue
      routing: auth_user_routing

    - name: task_report_email_queue
      routing: task_report_routing
