spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    port: ${RABBITMQ_PORT}

#Use for sending notifications by email
email-exchange:
  name: email-exchange
  queues:
    registration:
      name: user_registration_email_queue
      routing: auth_user_routing

    task-report:
      name: task_report_email_queue
      routing: task_report_routing

