server:
  port: 0

spring:
  profiles:
    include:
      - rabbit-queues
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_AUTH_PORT}/${POSTGRES_AUTH_DB}
    username: ${POSTGRES_AUTH_USERNAME}
    password: ${POSTGRES_AUTH_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
  rabbit:
    host: localhost
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}
